// Sistema_vuelos.v1/vuelos-angular/src/app/layouts/admin-layout/admin-layout.component.ts
import { Component, inject } from '@angular/core';
import { RouterModule, Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { AuthStore } from '../../core/store/auth.store';

interface NavItem { path: string; label: string; icon: string; end?: boolean; }
interface NavGroup { label: string; items: NavItem[]; }

const NAV_GROUPS: NavGroup[] = [
  { label: 'General', items: [
    { path: '/admin', label: 'Dashboard', end: true, icon: 'M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6' },
  ]},
  { label: 'Vuelos', items: [
    { path: '/admin/flights',       label: 'Vuelos',          icon: 'M12 19l9 2-9-18-9 18 9-2zm0 0v-8' },
    { path: '/admin/segments',      label: 'Segmentos',       icon: 'M4 6h16M4 10h16M4 14h16M4 18h16' },
    { path: '/admin/flightclasses', label: 'Clases de Vuelo', icon: 'M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z' },
  ]},
  { label: 'Geografía & Flota', items: [
    { path: '/admin/airports',  label: 'Aeropuertos', icon: 'M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z' },
    { path: '/admin/airlines',  label: 'Aerolíneas',  icon: 'M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-2 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4' },
    { path: '/admin/aircraft',  label: 'Aeronaves',   icon: 'M12 19l9 2-9-18-9 18 9-2zm0 0v-8' },
    { path: '/admin/countries', label: 'Países',      icon: 'M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064' },
    { path: '/admin/cities',    label: 'Ciudades',    icon: 'M8 14v3m4-3v3m4-3v3M3 21h18M3 10h18M3 7l9-4 9 4M4 10h16v11H4V10z' },
  ]},
  { label: 'Operaciones', items: [
    { path: '/admin/reservations',   label: 'Reservas',        icon: 'M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253' },
    { path: '/admin/boarding-passes',label: 'Boarding Passes', icon: 'M15 5v2m0 4v2m0 4v2M5 5a2 2 0 00-2 2v3a2 2 0 110 4v3a2 2 0 002 2h14a2 2 0 002-2v-3a2 2 0 110-4V7a2 2 0 00-2-2H5z' },
    { path: '/admin/promotions',     label: 'Promociones',     icon: 'M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z' },
  ]},
  { label: 'Finanzas', items: [
    { path: '/admin/payments', label: 'Pagos',    icon: 'M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z' },
    { path: '/admin/invoices', label: 'Facturas', icon: 'M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z' },
  ]},
  { label: 'Sistema', items: [
    { path: '/admin/services', label: 'Servicios', icon: 'M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z' },
    { path: '/admin/users',    label: 'Usuarios',  icon: 'M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z' },
    { path: '/admin/audit',    label: 'Auditoría', icon: 'M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z' },
  ]},
];

@Component({
  selector: 'app-admin-layout',
  standalone: true,
  imports: [RouterModule, CommonModule],
  template: `
    <div class="min-h-screen flex bg-gray-100">
      <!-- Sidebar -->
      <aside class="w-60 bg-gray-900 flex flex-col">
        <div class="h-16 flex items-center px-5 border-b border-gray-800 flex-shrink-0">
          <div class="flex items-center gap-2 text-white font-bold">
            <svg class="w-5 h-5 text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8"/></svg>
            <span>Admin Panel</span>
          </div>
        </div>

        <nav class="flex-1 py-3 px-3 overflow-y-auto space-y-4">
          <div *ngFor="let group of navGroups">
            <p class="text-xs font-semibold text-gray-600 uppercase tracking-wider px-3 mb-1">{{ group.label }}</p>
            <div class="space-y-0.5">
              <a *ngFor="let item of group.items" [routerLink]="item.path"
                routerLinkActive="bg-blue-600 text-white"
                [routerLinkActiveOptions]="{ exact: !!item.end }"
                class="flex items-center gap-3 px-3 py-2 rounded-lg text-sm font-medium transition-colors text-gray-400 hover:text-white hover:bg-gray-800">
                <svg class="w-4 h-4 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" [attr.d]="item.icon"/>
                </svg>
                <span class="truncate">{{ item.label }}</span>
                <svg class="w-3 h-3 ml-auto opacity-40 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
              </a>
            </div>
          </div>
        </nav>

        <div class="border-t border-gray-800 p-4 flex-shrink-0">
          <div class="flex items-center gap-3 mb-3">
            <div class="w-8 h-8 rounded-full bg-blue-600 flex items-center justify-center text-white text-xs font-bold flex-shrink-0">
              {{ auth.user()?.firstName?.charAt(0) }}
            </div>
            <div class="min-w-0">
              <p class="text-sm font-medium text-white truncate">{{ auth.user()?.firstName }} {{ auth.user()?.firstLastName }}</p>
              <p class="text-xs text-gray-500 truncate">{{ auth.user()?.email }}</p>
            </div>
          </div>
          <button (click)="logout()" class="w-full flex items-center gap-2 text-xs text-gray-500 hover:text-red-400 transition-colors py-1">
            <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"/></svg>
            Cerrar sesión
          </button>
        </div>
      </aside>

      <!-- Contenido -->
      <div class="flex-1 flex flex-col overflow-auto">
        <main class="flex-1 p-8"><router-outlet /></main>
      </div>
    </div>
  `,
})
export class AdminLayoutComponent {
  auth       = inject(AuthStore);
  router     = inject(Router);
  navGroups  = NAV_GROUPS;

  logout() {
    this.auth.clearAuth();
    this.router.navigate(['/login']);
  }
}

// Sistema_vuelos.v1/vuelos-frontend/src/components/layout/AdminLayout.tsx
// src/components/layout/AdminLayout.tsx
import { Outlet, NavLink, useNavigate } from 'react-router-dom';
import {
  Plane, MapPin, Building2, BookOpen, Users, LayoutDashboard,
  LogOut, ChevronRight, Globe, Building, PlaneTakeoff, Tag,
  Layers, CreditCard, FileText, Ticket, ShieldCheck, Wrench,
} from 'lucide-react';
import { useAuthStore } from '@/store/auth.store';
import { cn } from '@/lib/utils';

const NAV_GROUPS = [
  {
    label: 'General',
    items: [
      { to: '/admin',              icon: LayoutDashboard, label: 'Dashboard',   end: true },
    ],
  },
  {
    label: 'Vuelos',
    items: [
      { to: '/admin/flights',      icon: Plane,           label: 'Vuelos' },
      { to: '/admin/segments',     icon: Layers,          label: 'Segmentos' },
      { to: '/admin/flightclasses',icon: Tag,             label: 'Clases de Vuelo' },
    ],
  },
  {
    label: 'Geografía & Flota',
    items: [
      { to: '/admin/airports',     icon: MapPin,          label: 'Aeropuertos' },
      { to: '/admin/airlines',     icon: Building2,       label: 'Aerolíneas' },
      { to: '/admin/aircraft',     icon: PlaneTakeoff,    label: 'Aeronaves' },
      { to: '/admin/countries',    icon: Globe,           label: 'Países' },
      { to: '/admin/cities',       icon: Building,        label: 'Ciudades' },
    ],
  },
  {
    label: 'Operaciones',
    items: [
      { to: '/admin/reservations', icon: BookOpen,        label: 'Reservas' },
      { to: '/admin/boarding-passes', icon: Ticket,       label: 'Boarding Passes' },
      { to: '/admin/promotions',   icon: Tag,             label: 'Promociones' },
    ],
  },
  {
    label: 'Finanzas',
    items: [
      { to: '/admin/payments',     icon: CreditCard,      label: 'Pagos' },
      { to: '/admin/invoices',     icon: FileText,        label: 'Facturas' },
    ],
  },
  {
    label: 'Sistema',
    items: [
      { to: '/admin/services',     icon: Wrench,          label: 'Servicios' },
      { to: '/admin/users',        icon: Users,           label: 'Usuarios' },
      { to: '/admin/audit',        icon: ShieldCheck,     label: 'Auditoría' },
    ],
  },
];

export function AdminLayout() {
  const { user, clearAuth } = useAuthStore();
  const navigate = useNavigate();

  return (
    <div className="min-h-screen flex bg-gray-100">
      {/* ── Sidebar ── */}
      <aside className="w-60 bg-gray-900 flex flex-col">
        {/* Logo */}
        <div className="h-16 flex items-center px-5 border-b border-gray-800 flex-shrink-0">
          <div className="flex items-center gap-2 text-white font-bold">
            <Plane className="w-5 h-5 text-blue-400" />
            <span>Admin Panel</span>
          </div>
        </div>

        {/* Nav */}
        <nav className="flex-1 py-3 px-3 overflow-y-auto space-y-4">
          {NAV_GROUPS.map((group) => (
            <div key={group.label}>
              <p className="text-xs font-semibold text-gray-600 uppercase tracking-wider px-3 mb-1">
                {group.label}
              </p>
              <div className="space-y-0.5">
                {group.items.map(({ to, icon: Icon, label, ...rest }) => (
                  <NavLink
                    key={to}
                    to={to}
                    end={'end' in rest ? (rest as any).end : undefined}
                    className={({ isActive }) =>
                      cn(
                        'flex items-center gap-3 px-3 py-2 rounded-lg text-sm font-medium transition-colors',
                        isActive
                          ? 'bg-blue-600 text-white'
                          : 'text-gray-400 hover:text-white hover:bg-gray-800'
                      )
                    }
                  >
                    <Icon className="w-4 h-4 flex-shrink-0" />
                    <span className="truncate">{label}</span>
                    <ChevronRight className="w-3 h-3 ml-auto opacity-40 flex-shrink-0" />
                  </NavLink>
                ))}
              </div>
            </div>
          ))}
        </nav>

        {/* User + Logout */}
        <div className="border-t border-gray-800 p-4 flex-shrink-0">
          <div className="flex items-center gap-3 mb-3">
            <div className="w-8 h-8 rounded-full bg-blue-600 flex items-center justify-center text-white text-xs font-bold flex-shrink-0">
              {user?.firstName.charAt(0)}
            </div>
            <div className="min-w-0">
              <p className="text-sm font-medium text-white truncate">{user?.firstName} {user?.firstLastName}</p>
              <p className="text-xs text-gray-500 truncate">{user?.email}</p>
            </div>
          </div>
          <button
            onClick={() => { clearAuth(); navigate('/login'); }}
            className="w-full flex items-center gap-2 text-xs text-gray-500 hover:text-red-400 transition-colors py-1"
          >
            <LogOut className="w-3.5 h-3.5" />
            Cerrar sesión
          </button>
        </div>
      </aside>

      {/* ── Contenido ── */}
      <div className="flex-1 flex flex-col overflow-auto">
        <main className="flex-1 p-8">
          <Outlet />
        </main>
      </div>
    </div>
  );
}
